[tool.poetry]
name = "matrix-loading-programs"
version = "0.1.0"
description = "Matrix data analysis with pip and Poetry"
authors = ["Stepan Stepanyan"]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.1.0"
numpy = "^1.25.0"
matplotlib = "^3.7.2"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"